name: Run Deploy
on: 
    pull_request:
        types:
            - closed

jobs:
  run_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - name: install dependencies
        run: yarn
      - name: run lint
        run: yarn lint
      - name: run build
        run: yarn build
